# Generated by Django 6.0.6 on 2026-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
