# Generated by Django 6.0.6 on 2026-07-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='pieces_per_carton',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
