# Generated by Django 6.0.6 on 2026-07-17 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variant_pieces_per_carton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='pieces_per_carton',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
